Mycloud/urls.py
from django.urls import path
from . import views

app_name = 'Mycloud'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'), 
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('home/', views.home, name='home'),
    path('upload/', views.upload, name='upload'),
    path('delete/<int:pk>/', views.delete_file, name='delete_file'),
    path('imageupload/', views.imageupload, name='imageupload'),
    path('delete_image/<int:pk>/', views.delete_image, name='delete_image')

]

cloud/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles import views

urlpatterns = [
    path('Mycloud/', include('Mycloud.urls')),
    path('admin/', admin.site.urls),
]

#to direct the url in development to create a file in local as media where documents will be saved
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                            document_root=settings.MEDIA_ROOT)

Mycloud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.TextField(max_length=500)
    location = models.CharField(max_length=30, blank=True)
    #portfolio_site = models.URLField(blank=True)
    # profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.username
    
@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        instance.profile.save()
        
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/%Y/%m/%d/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    def __str__(self):
        return self.description

    def delete(self, *args, **kwargs):
        self.document.delete()
        super().delete(*args, **kwargs)

class ImageUpload(models.Model):
    caption = models.CharField(max_length=21, blank=True)
    image = models.ImageField(upload_to ='images/%y%m%d')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    #user = models.ForeignKey(User, on_delete=CASCADE)

    def delete(self, *args, **kwargs):
        self.image.delete()
        super().delete(*args, **kwargs)

Mycloud/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Mycloud.form import SignUpForm, UserLoginForm, DocumentForm, ImageForm
from Mycloud.models import Document, ImageUpload #to import the fileupload model
from django.contrib import messages
from django.contrib.sessions.models import Session
from django.contrib.auth import logout
from django.contrib.auth.models import User



# Create your views here.
def index(request):
    return render(request,'Mycloud/index.html')

@login_required
def home(request):
    documents = Document.objects.filter(user=request.user)
    images = ImageUpload.objects.all()
    return render(request, 'Mycloud/home.html', {
        "documents": documents, "images": images
    })

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            messages.success(request, 'Account created successfully')
            username = form.cleaned_data.get('username') 
            raw_password = form.cleaned_data.get('password1')
            user.save()
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect( 'Mycloud:login' )
        else:
            return render(request, 'Mycloud/signup.html', {'form': form})
    else:
        form = SignUpForm()
        return render(request, 'Mycloud/signup.html', {'form': form})

def user_login(request):
    form = UserLoginForm(request.POST)
    if request.method == 'POST': 
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password) #authenticate confirm if username and password correspond
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('Mycloud:index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'Mycloud/login.html', {'form': form})

    @login_required #trying to use decorator, though the login code didnt get here
    def special(request):
        return HttpResponse("You are logged in !")

def user_logout(request):# users logout function
    logout(request)
    #return HttpResponse("You are logged out !")# logout function end here
    return redirect('Mycloud:index') # just a line i choose to add in case i decide to redirect to index page

@login_required
def upload(request): #function for users to upload files
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES) #expect  a doc
        if form.is_valid():
            #form.save()
            newdoc = Document(document = request.FILES['document'])
            newdoc.user = request.user
            
            form=newdoc.save()
            #documents = form.instance
            #return render(request, Mycloud/home.html, {'form':form, 'documents':documents})
            return redirect('Mycloud:home')
    else:
        form = DocumentForm()
    return render(request, 'Mycloud/upload.html', {  'form': form }) 

@login_required
def imageupload(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect ('Mycloud:home')
    else:
        form = ImageForm
    return render(request, 'Mycloud/imageupload.html', {  'form': form } )

def delete_file(request, pk):
    if request.method == "POST":
        documents = Document.objects.get(pk=pk)
        documents.delete()
    return redirect('Mycloud:home')


def delete_image(request, pk):
    if request.method == "POST":
        images = ImageUpload.objects.get(pk=pk)
        images.delete()
    return redirect('Mycloud:home')

Mycloud/templates/Mycloud/home.html
{% extends "Mycloud/static.html" %}
{% load static %}

{% block content %}        
    {% block body %}
        {%if user.is_authenticated%}
            {% block username %}
                {% csrf_token %}                
                <h2> {{ user.username }}dashboard</h2>                
            {% endblock %}            
            {% block upload %}
                {% csrf_token %}
                <p><a href="{% url 'Mycloud:upload' %}" class="btn btn-primary">upload doc</a></p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>description</th>
                            <th>files</th>
                            <th>download</th>
                            <th>delete</th>                                
                        </tr>
                    </thead>

                    <tbody>                                                        
                        {% for file in documents %}                                 
                            <tr>                                    
                                <td>{{file.description}}</td>
                                <td>{{file.document}}</td> 
                                <td> <a href="{{file.document.url}}" class="btn btn-primary btn-sm" target="_blank">download file</a></td>
                                <td>
                                    <form method="POST" action="{% url 'Mycloud:delete_file' file.pk %}">
                                        {%csrf_token%}
                                        <button type="submit" class="btn btn-danger">delete</button>
                                    </form>                                        
                                </td>
                            </tr>                             
                        {% endfor %}     
                    </tbody>
                </table>
                <p><a href="{% url 'Mycloud:imageupload' %}" class="btn btn-primary">upload image</a></p>

                <table class="table">
                    <thead >
                        <tr>
                            <th>Caption</th>
                            <th>Image</th>
                            <th>delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for image in images %}
                            <tr> 
                              
                                <td>{{ image.caption}}</td>
                                <td>
                                    {% if image.image %}
                                    <img src="{{image.image.url}}"alt="{{image.caption}}" style="width:100px";>
                                    {% endif %}
                                </td>
                                <td>
                                    <form method="POST" action="{% url 'Mycloud:delete_image' image.pk %}">
                                        {%csrf_token%}
                                        <button type="submit" class="btn btn-danger">delete</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <p><a href="{% url 'Mycloud:index' %}">{{ index }}Go to home</a></p>
            {% endblock %}
            
        {% else %}
            <h3><a href="{% url 'Mycloud:index' %}">{{ login }}login or create an account</a></h3>
        {% endif %}
    {% endblock %}
{% endblock %}

Mycloud/templates/Mycloud/imageupload.html
{% extends "Mycloud/static.html" %}

{% block content %}
<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Upload Image</button>
</form>
{% endblock %}

Mycloud/templates/Mycloud/index.html
{% block content %}

  {% load static %}
  
  {% block body_block %}
    {% csrf_token %}
  {% endblock %}
  

    <h1>Welcome to the cloud !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <h3><a href="{% url 'Mycloud:home' %}">{{ dashboard }}go to dashboard</a></h3>
        <h3><a href="{% url 'Mycloud:logout' %}">{{ logout }}logout</a></h3>


    {% else %}
        <h2><a href="{% url 'Mycloud:signup' %}">{{ signup }}Sign up</a></h2>
        <h2><a href="{% url 'Mycloud:login' %}">{{ login }}Login</a></h2>
    {% endif %}
{% endblock %}

Mycloud/templates/Mycloud/login.html
{% extends "Mycloud/static.html" %}
{% block content %}
      {% load static %}
      
      {% block title %}
            Login
      {% endblock %}
      <h1>Login:</h1>
      {% block login %}
      <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" name="" value="login" class="btn btn-primary">
      </form>
      <h2><a href="{% url 'Mycloud:signup' %}" class="btn btn-primary">{{ signup }}Sign up</a></h2>
      {% endblock %}
{% endblock %}

Mycloud/templates/Mycloud/signup.html
{% block content %}
  {% load static %}
  
  <h2>sign up</h2>

  <form action="{% url 'Mycloud:signup' %}" method="POST">
    
    {% csrf_token %}
    

    {% for field in form %}
      <p>
        {{field.label_tag}}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color:grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color:red">{{ error }}</p>
        {% endfor %}
      </p>  
    {% endfor %}
      <input type='submit' id='submit' name='signup' value='Sign up' class="btn btn-primary">
  </form>

{% endblock %}

Mycloud/templates/Mycloud/static.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>cloud</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

    <body>
      {% block content %}
      {% endblock %}
    </body>
    <footer>
        <h3><a href="{% url 'Mycloud:logout' %}">{{ logout }}logout</a></h3>
    </footer>
</html>

Mycloud/templates/Mycloud/upload.html
{% extends "Mycloud/static.html" %}

{% block content %}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Upload</button>
  </form>

  <p><a href="{% url 'Mycloud:home' %}">Return to home</a></p>
{% endblock %}